import type { Option } from "@/components/ui/multi-select";

export const storyType = [
  "ballad",
  "lyric-poem",
  "novella",
  "short-story",
  "stage-play",
];

export const genres: Option[] = [
  { value: "adventure", label: "Adventure" },
  { value: "biographical-fiction", label: "Biographical Fiction" },
  { value: "children", label: "Children" },
  { value: "comedy", label: "Comedy" },
  { value: "crime", label: "Crime" },
  { value: "cyberpunk", label: "Cyberpunk" },
  { value: "detective", label: "Detective" },
  { value: "drama", label: "Drama" },
  { value: "dystopian", label: "Dystopian" },
  { value: "epic", label: "Epic" },
  { value: "fairy-tale", label: "Fairy Tale" },
  { value: "fantasy", label: "Fantasy" },
  { value: "gothic", label: "Gothic" },
  { value: "historical-fiction", label: "Historical Fiction" },
  { value: "horror", label: "Horror" },
  { value: "literary-fiction", label: "Literary Fiction" },
  { value: "magical-realism", label: "Magical Realism" },
  { value: "memoir", label: "Memoir" },
  { value: "mystery", label: "Mystery" },
  { value: "mythology", label: "Mythology" },
  { value: "non-fiction-narrative", label: "Non-Fiction Narrative" },
  { value: "paranormal", label: "Paranormal" },
  { value: "post-apocalyptic", label: "Post-Apocalyptic" },
  { value: "romance", label: "Romance" },
  { value: "satire", label: "Satire" },
  { value: "science-fiction", label: "Science Fiction" },
  { value: "short-story-collection", label: "Short Story Collection" },
  { value: "slice-of-life", label: "Slice of Life" },
  { value: "steampunk", label: "Steampunk" },
  { value: "thriller", label: "Thriller" },
  { value: "urban-fantasy", label: "Urban Fantasy" },
  { value: "western", label: "Western" },
  { value: "young-adult", label: "Young Adult" },
];

export const themes: Option[] = [
  { value: "alienation", label: "Alienation" },
  { value: "ambition", label: "Ambition" },
  { value: "betrayal", label: "Betrayal" },
  { value: "chaos", label: "Chaos" },
  { value: "change", label: "Change" },
  { value: "class-struggle", label: "Class Struggle" },
  { value: "colonialism", label: "Colonialism" },
  { value: "coming-of-age", label: "Coming of Age" },
  { value: "compassion", label: "Compassion" },
  { value: "competition", label: "Competition" },
  { value: "community", label: "Community" },
  { value: "cooperation", label: "Cooperation" },
  { value: "corruption", label: "Corruption" },
  { value: "courage", label: "Courage" },
  { value: "cultural-identity", label: "Cultural Identity" },
  { value: "death", label: "Death" },
  { value: "desire", label: "Desire" },
  { value: "destiny", label: "Destiny" },
  { value: "destiny-vs-choice", label: "Destiny vs Choice" },
  { value: "doubt", label: "Doubt" },
  { value: "dreams", label: "Dreams" },
  { value: "escape", label: "Escape" },
  { value: "equality", label: "Equality" },
  { value: "exile", label: "Exile" },
  { value: "faith", label: "Faith" },
  { value: "family", label: "Family" },
  { value: "fame", label: "Fame" },
  { value: "fear", label: "Fear" },
  { value: "fear-of-the-unknown", label: "Fear of the Unknown" },
  { value: "forgiveness", label: "Forgiveness" },
  { value: "freedom", label: "Freedom" },
  { value: "friendship", label: "Friendship" },
  { value: "gender", label: "Gender" },
  { value: "glory", label: "Glory" },
  { value: "good-vs-evil", label: "Good vs Evil" },
  { value: "greed", label: "Greed" },
  { value: "greed-vs-generosity", label: "Greed vs Generosity" },
  { value: "grief", label: "Grief" },
  { value: "healing", label: "Healing" },
  { value: "honor", label: "Honor" },
  { value: "hope", label: "Hope" },
  { value: "identity", label: "Identity" },
  { value: "illusion", label: "Illusion" },
  { value: "imprisonment", label: "Imprisonment" },
  { value: "innovation", label: "Innovation" },
  { value: "innocence", label: "Innocence" },
  { value: "isolation", label: "Isolation" },
  { value: "justice", label: "Justice" },
  { value: "justice-vs-injustice", label: "Justice vs Injustice" },
  { value: "justice-vs-mercy", label: "Justice vs Mercy" },
  { value: "knowledge", label: "Knowledge" },
  { value: "legacy", label: "Legacy" },
  { value: "loyalty", label: "Loyalty" },
  { value: "love", label: "Love" },
  { value: "loss", label: "Loss" },
  { value: "madness", label: "Madness" },
  { value: "materialism", label: "Materialism" },
  { value: "memory", label: "Memory" },
  { value: "migration", label: "Migration" },
  { value: "morality", label: "Morality" },
  { value: "nature", label: "Nature" },
  { value: "nightmares", label: "Nightmares" },
  { value: "order", label: "Order" },
  { value: "order-vs-disorder", label: "Order vs Disorder" },
  { value: "parenthood", label: "Parenthood" },
  { value: "peace", label: "Peace" },
  { value: "poverty", label: "Poverty" },
  { value: "power", label: "Power" },
  { value: "prejudice", label: "Prejudice" },
  { value: "racism", label: "Racism" },
  { value: "rebellion", label: "Rebellion" },
  { value: "rebirth", label: "Rebirth" },
  { value: "redemption", label: "Redemption" },
  { value: "responsibility", label: "Responsibility" },
  { value: "resilience", label: "Resilience" },
  { value: "revenge", label: "Revenge" },
  { value: "romantic-idealism", label: "Romantic Idealism" },
  { value: "sacrifice", label: "Sacrifice" },
  { value: "sacred-vs-profane", label: "Sacred vs Profane" },
  { value: "self-discovery", label: "Self Discovery" },
  { value: "sibling-rivalry", label: "Sibling Rivalry" },
  { value: "silence", label: "Silence" },
  { value: "spirituality", label: "Spirituality" },
  { value: "survival", label: "Survival" },
  { value: "technology", label: "Technology" },
  { value: "temptation", label: "Temptation" },
  { value: "time", label: "Time" },
  { value: "tradition", label: "Tradition" },
  { value: "tradition-vs-progress", label: "Tradition vs Progress" },
  { value: "transformation", label: "Transformation" },
  { value: "trust", label: "Trust" },
  { value: "trust-vs-betrayal", label: "Trust vs Betrayal" },
  { value: "truth", label: "Truth" },
  { value: "violence", label: "Violence" },
  { value: "voice", label: "Voice" },
  { value: "war", label: "War" },
  { value: "wealth", label: "Wealth" },
  { value: "wisdom", label: "Wisdom" },
];

export const tones: Option[] = [
  { value: "adventurous", label: "Adventurous" },
  { value: "authoritative", label: "Authoritative" },
  { value: "bittersweet", label: "Bittersweet" },
  { value: "bleak", label: "Bleak" },
  { value: "calm", label: "Calm" },
  { value: "casual", label: "Casual" },
  { value: "chaotic", label: "Chaotic" },
  { value: "cheerful", label: "Cheerful" },
  { value: "colloquial", label: "Colloquial" },
  { value: "confessional", label: "Confessional" },
  { value: "contemplative", label: "Contemplative" },
  { value: "critical", label: "Critical" },
  { value: "cynical", label: "Cynical" },
  { value: "dark", label: "Dark" },
  { value: "detached", label: "Detached" },
  { value: "disturbing", label: "Disturbing" },
  { value: "dramatic", label: "Dramatic" },
  { value: "eccentric", label: "Eccentric" },
  { value: "elegiac", label: "Elegiac" },
  { value: "emotional", label: "Emotional" },
  { value: "energetic", label: "Energetic" },
  { value: "epic", label: "Epic" },
  { value: "ethereal", label: "Ethereal" },
  { value: "fantastical", label: "Fantastical" },
  { value: "formal", label: "Formal" },
  { value: "gloomy", label: "Gloomy" },
  { value: "gothic", label: "Gothic" },
  { value: "heroic", label: "Heroic" },
  { value: "hopeful", label: "Hopeful" },
  { value: "hopeful-romantic", label: "Hopeful Romantic" },
  { value: "humorous", label: "Humorous" },
  { value: "informal", label: "Informal" },
  { value: "intense", label: "Intense" },
  { value: "ironic", label: "Ironic" },
  { value: "lighthearted", label: "Lighthearted" },
  { value: "lyrical", label: "Lyrical" },
  { value: "matter-of-fact", label: "Matter of Fact" },
  { value: "meditative", label: "Meditative" },
  { value: "melancholy", label: "Melancholy" },
  { value: "minimalist", label: "Minimalist" },
  { value: "mysterious", label: "Mysterious" },
  { value: "nostalgic", label: "Nostalgic" },
  { value: "objective", label: "Objective" },
  { value: "objective-reporting", label: "Objective Reporting" },
  { value: "ominous", label: "Ominous" },
  { value: "optimistic", label: "Optimistic" },
  { value: "ornate", label: "Ornate" },
  { value: "passionate", label: "Passionate" },
  { value: "philosophical", label: "Philosophical" },
  { value: "playful", label: "Playful" },
  { value: "pessimistic", label: "Pessimistic" },
  { value: "rebellious", label: "Rebellious" },
  { value: "restrained", label: "Restrained" },
  { value: "romantic", label: "Romantic" },
  { value: "romanticized", label: "Romanticized" },
  { value: "sarcastic", label: "Sarcastic" },
  { value: "satirical", label: "Satirical" },
  { value: "scientific", label: "Scientific" },
  { value: "sentimental", label: "Sentimental" },
  { value: "serious", label: "Serious" },
  { value: "solemn", label: "Solemn" },
  { value: "spiritual", label: "Spiritual" },
  { value: "subjective", label: "Subjective" },
  { value: "suspenseful", label: "Suspenseful" },
  { value: "surreal", label: "Surreal" },
  { value: "tense", label: "Tense" },
  { value: "tragic", label: "Tragic" },
  { value: "urgent", label: "Urgent" },
  { value: "vivid", label: "Vivid" },
  { value: "whimsical", label: "Whimsical" },
];
