export const user_sessions = [
  {
    "id": "f47ac10b-58cc-4372-a567-0e02b2c3d479",
    "session_id": "sess_2024_001",
    "user_id": "user_123",
    "session_type": "language_tutor",
    "title": "Ordering Food at a Restaurant",
    "description": "Practiced ordering food, asking about ingredients, and requesting the bill at a Spanish restaurant",
    "feedback": "Good progress with food vocabulary! Work on using 'me gustaría' more naturally. Your pronunciation of 'r' sounds improved significantly.",
    "duration": 900,
    "language": "spanish",
    "proficiency_level": "B1",
    "formality": "casual",
    "role_scenario": "You are a tourist in Madrid ordering dinner at a traditional tapas restaurant. Ask about recommendations and dietary restrictions.",
    "target_vocabulary": ["me gustaría", "recomendación", "sin gluten", "la cuenta", "delicioso", "picante"],
    "created_at": "2024-07-22T14:30:00Z"
  },
  {
    "id": "550e8400-e29b-41d4-a716-446655440001",
    "session_id": "sess_2024_002",
    "user_id": "user_123",
    "session_type": "language_tutor",
    "title": "Job Interview Practice",
    "description": "Mock job interview for a marketing position, discussing experience and asking questions about the company",
    "feedback": "Excellent use of formal language structures! Focus on past tense consistency when describing work experience. Your confidence has improved.",
    "duration": 1200,
    "language": "spanish",
    "proficiency_level": "B2",
    "formality": "formal",
    "role_scenario": "You're interviewing for a digital marketing role at a Spanish tech startup. Discuss your experience and ask thoughtful questions.",
    "target_vocabulary": ["experiencia laboral", "logros", "desafíos", "equipo", "objetivos", "crecimiento profesional"],
    "created_at": "2024-07-21T10:15:00Z"
  },
  {
    "id": "6ba7b810-9dad-11d1-80b4-00c04fd430c8",
    "session_id": "sess_2024_003",
    "user_id": "user_123",
    "session_type": "brainstorming",
    "title": "Travel Blog Content Ideas",
    "description": "Brainstormed creative content ideas for a travel blog focusing on sustainable tourism in Latin America",
    "feedback": "Great creative thinking! Your ideas about eco-tourism were well-structured. Consider developing the cultural exchange angle further.",
    "duration": 600,
    "language": "spanish",
    "proficiency_level": "B1",
    "formality": "casual",
    "role_scenario": "Brainstorm engaging content ideas for a travel blog about sustainable adventures in South America",
    "target_vocabulary": ["turismo sostenible", "aventura", "cultura local", "impacto ambiental", "experiencias auténticas"],
    "created_at": "2024-07-20T16:45:00Z"
  },
  {
    "id": "6ba7b811-9dad-11d1-80b4-00c04fd430c8",
    "session_id": "sess_2024_004",
    "user_id": "user_123",
    "session_type": "language_tutor",
    "title": "Doctor's Appointment",
    "description": "Roleplay visiting a doctor to discuss recurring headaches and understand treatment options",
    "feedback": "Well done describing symptoms! Practice using more medical vocabulary and asking follow-up questions about treatments.",
    "duration": 750,
    "language": "spanish",
    "proficiency_level": "A2",
    "formality": "formal",
    "role_scenario": "You have an appointment with a Spanish doctor to discuss recurring headaches and explore treatment options",
    "target_vocabulary": ["dolor de cabeza", "síntomas", "frecuencia", "tratamiento", "medicamento", "cita médica"],
    "created_at": "2024-07-19T11:20:00Z"
  },
  {
    "id": "6ba7b812-9dad-11d1-80b4-00c04fd430c8",
    "session_id": "sess_2024_005",
    "user_id": "user_123",
    "session_type": "language_tutor",
    "title": "Asking for Directions",
    "description": "Practiced asking for and understanding directions to various landmarks in Barcelona",
    "feedback": "Good basic direction vocabulary! Work on understanding more complex route descriptions and using landmarks in your questions.",
    "duration": 480,
    "language": "spanish",
    "proficiency_level": "A1",
    "formality": "casual",
    "role_scenario": "You're lost in Barcelona and need to ask locals for directions to famous landmarks like Sagrada Familia and Park Güell",
    "target_vocabulary": ["¿dónde está?", "cerca", "lejos", "derecha", "izquierda", "todo recto", "semáforo"],
    "created_at": "2024-07-18T09:30:00Z"
  },
  {
    "id": "6ba7b813-9dad-11d1-80b4-00c04fd430c8",
    "session_id": "sess_2024_006",
    "user_id": "user_123",
    "session_type": "language_tutor",
    "title": "Negotiating Apartment Rent",
    "description": "Advanced conversation about negotiating rental terms and discussing apartment features with a landlord",
    "feedback": "Impressive negotiation skills! Your use of conditional tense was excellent. Focus on more persuasive language structures.",
    "duration": 1050,
    "language": "spanish",
    "proficiency_level": "B2",
    "formality": "formal",
    "role_scenario": "You're interested in renting an apartment in Madrid and need to negotiate the monthly rent and lease terms with the landlord",
    "target_vocabulary": ["alquiler", "fianza", "gastos incluidos", "condiciones", "negociar", "contrato"],
    "created_at": "2024-07-17T13:15:00Z"
  },
  {
    "id": "6ba7b814-9dad-11d1-80b4-00c04fd430c8",
    "session_id": "sess_2024_007",
    "user_id": "user_123",
    "session_type": "brainstorming",
    "title": "Small Business Marketing Strategy",
    "description": "Discussed creative marketing approaches for a local Spanish bakery looking to attract younger customers",
    "feedback": "Innovative ideas! Your understanding of target demographics was solid. Explore more digital marketing concepts in Spanish.",
    "duration": 720,
    "language": "spanish",
    "proficiency_level": "B1",
    "formality": "casual",
    "role_scenario": "Help brainstorm modern marketing strategies for a traditional Spanish bakery wanting to attract millennial customers",
    "target_vocabulary": ["estrategia", "público objetivo", "redes sociales", "marca", "innovación", "tendencias"],
    "created_at": "2024-07-16T15:00:00Z"
  },
  {
    "id": "6ba7b815-9dad-11d1-80b4-00c04fd430c8",
    "session_id": "sess_2024_008",
    "user_id": "user_123",
    "session_type": "language_tutor",
    "title": "Shopping for Clothes",
    "description": "Practiced shopping vocabulary, asking about sizes, colors, and prices at a Spanish clothing store",
    "feedback": "Great improvement with numbers and clothing vocabulary! Practice asking about different materials and return policies.",
    "duration": 540,
    "language": "spanish",
    "proficiency_level": "A2",
    "formality": "casual",
    "role_scenario": "You're shopping for a new outfit at a Spanish department store and need help finding the right size and style",
    "target_vocabulary": ["talla", "color", "precio", "probador", "descuento", "algodón", "devolver"],
    "created_at": "2024-07-15T12:45:00Z"
  }
]