export const userSessions = [
  {
    "id": "a1b2c3d4-e5f6-7890-abcd-1234567890ab",
    "session_id": "sess_2025_001",
    "user_id": "user_123",
    "title": "Asking out the girl who always sits at the same library table for weekend coffee",
    "role_scenario": "You see the same girl at the library every afternoon and finally want to invite her for coffee this weekend in the park café.",
    "feedback": "¡Excelente esfuerzo! A nivel general tu fraseo transmite amabilidad, pero para sonar más natural y respetuoso necesitamos ajustar varios detalles. Primero, evita «quieres» cuando invites a alguien que apenas conoces; «¿Te gustaría tomar un café conmigo este fin de semana?» suena más cortés y menos directo. Recuerda que «weekend» no existe en español; usa «este fin de semana». Además, «coger un café» puede sonar brusco en algunos países; «tomar un café» es neutro. Por último, une «con migo» en una sola palabra: «conmigo». Para redondear, podrías añadir un pequeño cumplido antes de la invitación: «Siempre te veo por aquí y me pareces muy interesante. ¿Te gustaría tomar un café conmigo este sábado por la tarde?»",
    "target_vocabulary": ["biblioteca", "tomar un café", "este fin de semana", "conmigo", "invitación", "cumplido", "interesante", "sábado por la tarde", "gesto amable", "coqueteo sutil", "confianza", "primera cita", "sentarse", "libros", "quedar", "encanto", "timidez", "oportunidad", "conversación", "mirada"],
    "user_audio": "mp3 file",
    "created_at": "2025-08-07T09:15:00Z"
  },
  {
    "id": "b2c3d4e5-f6a7-8901-bcde-2345678901bc",
    "session_id": "sess_2025_002",
    "user_id": "user_123",
    "title": "Requesting a 10 % raise after two years with the company",
    "role_scenario": "You have worked at the company for two full years and want to request a 10 % salary increase during a meeting with your manager.",
    "feedback": "Has captado la idea clave, pero un tema tan delicado requiere mayor formalidad. En lugar de «quiero hablar», empieza con «Me gustaría hablar sobre mi desempeño y posibilidad de un aumento». Escribe «dos años» con letras. Para el porcentaje, di «un aumento del diez por ciento». Además, «subida» es coloquial; utiliza «aumento» o «incremento». Para estructurar tu argumento: (1) agradecimiento, (2) logros concretos, (3) solicitud justificada, (4) disposición a negociar. Ejemplo: «Durante estos dos años he aumentado las ventas en un 18 %. Por ello, solicito un aumento del 10 %, aunque estoy abierto a conversar otras cifras que consideren justas».",
    "target_vocabulary": ["aumento", "reconocimiento", "desempeño", "salario", "negociación", "compromiso", "logros", "méritos", "justificar", "incremento", "trayectoria", "productividad", "responsabilidad", "contribuciones", "evaluación", "perspectiva", "equidad", "beneficios", "retribución", "diálogo"],
    "user_audio": "mp3 file",
    "created_at": "2025-08-07T09:30:00Z"
  },
  {
    "id": "c3d4e5f6-a7b8-9012-cdef-3456789012cd",
    "session_id": "sess_2025_003",
    "user_id": "user_123",
    "title": "Calling sister-in-law to plan a secret 30th birthday party for your wife",
    "role_scenario": "You call your wife’s sister to organize a surprise 30th birthday party without letting your wife find out.",
    "feedback": "¡Buena intención! Para mayor precisión, sustituye «sin ella sabe» por «sin que se entere» (subjuntivo). «Su trigésimo cumpleaños» suena más natural que «30 cumpleaños». Además, «¿Podemos quedar?» queda corto; pregunta «¿Podríamos quedar para hablar de los preparativos?» para asegurar una reunión. Añade detalles: fecha tentativa, lista de invitados, temática y quién se encarga del pastel. Ejemplo completo: «¿Te parece si quedamos el jueves a las seis en el café de la esquina para organizar la fiesta sorpresa de su trigésimo cumpleaños sin que se entere?»",
    "target_vocabulary": ["sorpresa", "cumpleaños", "sin que se entere", "quedar", "preparativos", "invitados", "pastel", "temática", "hermana", "decoración", "regalo", "celebración", "secreto", "complicidad", "detalles", "fecha", "lugar", "confirmar", "colaborar", "ilusión"],
    "user_audio": "mp3 file",
    "created_at": "2025-08-07T09:45:00Z"
  },
  {
    "id": "d4e5f6a7-b8c9-0123-defa-4567890123de",
    "session_id": "sess_2025_004",
    "user_id": "user_123",
    "title": "Calling the dentist to reschedule tomorrow's appointment to next week because of a business trip",
    "role_scenario": "You need to move tomorrow’s dentist appointment to next week due to an unexpected work trip.",
    "feedback": "Tu mensaje es claro, pero falta cortesía y precisión. Empieza con «Disculpe las molestias, necesito cambiar la cita de mañana». Especifica «viaje de trabajo» y «la semana que viene». Para facilitar la reprogramación, propón dos franjas horarias: «¿Tendría disponibilidad el lunes por la mañana o el miércoles por la tarde?». No olvides confirmar la nueva fecha y agradecer: «Muchas gracias por su comprensión». Esto reduce idas y venidas.",
    "target_vocabulary": ["cambiar cita", "viaje de trabajo", "semana que viene", "disponibilidad", "molestias", "reprogramar", "franja horaria", "confirmar", "agradecer", "comprensión", "consulta", "horario", "urgencia", "formalidad", "llamada", "coordinar", "atención", "eficiencia", "flexibilidad", "paciente"],
    "user_audio": "mp3 file",
    "created_at": "2025-08-07T10:00:00Z"
  },
  {
    "id": "e5f6a7b8-c9d0-1234-efab-5678901234ef",
    "session_id": "sess_2025_005",
    "user_id": "user_123",
    "title": "Returning broken headphones to the store for a refund or exchange",
    "role_scenario": "You go back to the electronics shop because the headphones you bought yesterday have no sound in the left ear and you want to return them.",
    "feedback": "El vocabulario básico está bien, pero vamos a elevar la cortesía y claridad. «Dejaron de funcionar» es perfecto para describir el fallo. Para el canal izquierdo, di «el auricular izquierdo no emite sonido». «¿Puedo devolverlos?» es correcto, pero puedes añadir «o cambiarlos por otro par» para mostrar flexibilidad. Presenta la caja y el recibo: «Aquí tengo la caja original y el ticket de compra». Si la garantía aplica, menciónala: «Entiendo que tienen garantía de treinta días».",
    "target_vocabulary": ["devolver", "garantía", "auricular izquierdo", "dejar de funcionar", "recibo", "ticket", "caja original", "garantía", "electrónica", "fallo", "cliente", "política", "reembolso", "cambio", "prueba", "diagnóstico", "solución", "atención al cliente", "compra", "defecto"],
    "user_audio": "mp3 file",
    "created_at": "2025-08-07T10:15:00Z"
  },
  {
    "id": "f6a7b8c9-d0e1-2345-fabc-6789012345fa",
    "session_id": "sess_2025_006",
    "user_id": "user_123",
    "title": "Inviting three coworkers to a Saturday BBQ and asking them to bring drinks",
    "role_scenario": "You send a quick message to three teammates asking them to come to your place for a BBQ this Saturday and to bring beverages.",
    "feedback": "¡Muy cercano al natural! «Vamos a hacer una barbacoa este sábado» ya queda genial. Para pedirles que traigan bebidas, usa «¿Les importa traer bebidas/frías/refrescos?» en lugar del imperativo directo «traigan», que puede sonar brusco en chat informal. Añade hora y RSVP: «A partir de las 3 pm. Confírmame si vienen para calcular la carne». Si alguien tiene dieta especial, sugiere: «Si prefieren algo sin alcohol, avísenme».",
    "target_vocabulary": ["barbacoa", "traer", "bebidas", "sábado", "casa", "refrescos", "RSVP", "carne", "confirmar", "calculo", "dietético", "alcohol", "invitación", "compañeros", "reunión", "parrillada", "asado", "chorizo", "cerveza", "postre"],
    "user_audio": "mp3 file",
    "created_at": "2025-08-07T10:30:00Z"
  },
  {
    "id": "a7b8c9d0-e1f2-3456-abcd-7890123456ab",
    "session_id": "sess_2025_007",
    "user_id": "user_123",
    "title": "Texting the landlord about a leaking bathroom ceiling since last night",
    "role_scenario": "You message the landlord to report that water has been dripping from the bathroom ceiling since last night.",
    "feedback": "El mensaje es directo; vamos a incluir urgencia y cortesía. «Disculpe la hora, pero el techo del baño está goteando desde anoche» transmite inmediatez. Añade «es urgente» y ofrece disponibilidad: «¿Podría pasar hoy mismo? Estoy en casa hasta las 5». Si hay daños, adjunta foto: «Le envío una imagen para que vea la magnitud». Cierra con gracias y firma: «Gracias por su pronta atención, Ana P. – 2B».",
    "target_vocabulary": ["techo", "goteando", "baño", "urgente", "arreglar", "gotera", "plomería", "mantenimiento", "inundación", "imagen", "disponibilidad", "firma", "apartamento", "reparación", "agua", "daños", "pronto", "gracias", "reporte", "propietario"],
    "user_audio": "mp3 file",
    "created_at": "2025-08-07T10:45:00Z"
  },
  {
    "id": "b8c9d0e1-f2a3-4567-bcde-8901234567bc",
    "session_id": "sess_2025_008",
    "user_id": "user_123",
    "title": "Asking the neighbor to lend you a phone charger until tomorrow",
    "role_scenario": "You knock on your neighbor’s door to borrow a phone charger because yours broke and you need one until tomorrow.",
    "feedback": "La dirección del verbo es clave: «¿Podrías prestarme un cargador hasta mañana?». «Prestar» va del prestamista al receptor; «pedir prestado» es la otra cara. Añade cortesía: «Solo hasta que pueda comprar uno nuevo». Si tu vecino tiene varios modelos, pregunta: «¿Tienes uno de tipo C o solo iPhone?». Cierra ofreciendo devolverlo limpio: «Te lo devuelvo mañana por la tarde, bien enrollado».",
    "target_vocabulary": ["prestar", "hasta mañana", "cargador", "romperse", "vecino", "devolver", "tipo C", "iPhone", "cortesía", "favor", "apuro", "dispositivo", "batería", "cable", "rollito", "limpio", "gratitud", "préstamo", "conexión", "urgencia"],
    "user_audio": "mp3 file",
    "created_at": "2025-08-07T11:00:00Z"
  },
  {
    "id": "c9d0e1f2-a3b4-5678-cdef-9012345678cd",
    "session_id": "sess_2025_009",
    "user_id": "user_123",
    "title": "Calling the gym to cancel membership after moving to another city",
    "role_scenario": "You ring the gym to terminate your membership because you have relocated to a different city.",
    "feedback": "En lugar de «stop gym», di «Quiero cancelar la membresía». «Me he mudado a otra ciudad» indica cambio permanente. Si tu contrato exige aviso previo, pregunta: «¿Necesito enviar la solicitud por escrito?». Solicita confirmación por email: «¿Podrían enviarme un correo de confirmación?». Agradece y despidete: «Gracias por el servicio durante estos meses».",
    "target_vocabulary": ["cancelar", "membresía", "mudarse", "otra ciudad", "aviso previo", "contrato", "confirmación", "correo", "servicio", "cliente", "suscripción", "baja", "dirección", "comprobante", "trámite", "documentación", "finalizar", "relación", "aprecio", "despedida"],
    "user_audio": "mp3 file",
    "created_at": "2025-08-07T11:15:00Z"
  },
  {
    "id": "d0e1f2a3-b4c5-6789-defa-0123456789de",
    "session_id": "sess_2025_010",
    "user_id": "user_123",
    "title": "Reporting a stolen bike at the police station",
    "role_scenario": "You are at the police station explaining that your bicycle was stolen outside the supermarket two hours ago.",
    "feedback": "Prefiere la voz activa: «Me robaron la bicicleta hace dos horas frente al supermercado». Añade detalles clave: marca (Trek), color (azul celeste), número de serie si lo tienes. Describe cómo estaba atada: «Estaba asegurada con un candado U que también desapareció». Pregunta por el formulario de denuncia: «¿Necesito rellenar un parte?». Solicita copia para el seguro.",
    "target_vocabulary": ["robar", "bicicleta", "hace dos horas", "supermercado", "policía", "denuncia", "marca", "color", "número de serie", "candado", "parte", "seguro", "testigos", "cámara", "vigilancia", "formulario", "declaración", "copia", "robo", "prevención"],
    "user_audio": "mp3 file",
    "created_at": "2025-08-07T11:30:00Z"
  },
  {
    "id": "e1f2a3b4-c5d6-7890-abcd-1234567890ef",
    "session_id": "sess_2025_011",
    "user_id": "user_123",
    "title": "Calling the school to report your 8-year-old daughter has a fever and won't attend today",
    "role_scenario": "You ring the school office to inform them your eight-year-old daughter has a fever and will stay home today.",
    "feedback": "Di «Buenos días, llamo para avisar que mi hija de ocho años tiene fiebre y hoy no vendrá a clase». Proporciona el nombre completo y el curso: «Ella es Lucía García, 3º A». Si necesitan justificante, comenta: «En cuanto vaya al pediatra le enviaré el parte médico». Agradece: «Gracias por su comprensión».",
    "target_vocabulary": ["fiebre", "hija", "no vendrá", "hoy", "aviso", "clase", "justificante", "pediatra", "parte médico", "curso", "comprensión", "secretaría", "edad", "síntomas", "reposo", "medicina", "escuela", "llamada", "cuidados", "recuperación"],
    "user_audio": "mp3 file",
    "created_at": "2025-08-07T11:45:00Z"
  },
  {
    "id": "f2a3b4c5-d6e7-8901-bcde-2345678901fa",
    "session_id": "sess_2025_012",
    "user_id": "user_123",
    "title": "Booking a tennis court for Sunday at 5 pm for two hours",
    "role_scenario": "You phone the sports center to reserve a tennis court this Sunday from 5 pm to 7 pm.",
    "feedback": "«Quisiera reservar una cancha de tenis el domingo de 17:00 a 19:00» es perfecto. Añade disponibilidad: «¿Tienen alguna libre?». Pregunta por precio y cancelaciones: «¿Cuál es la tarifa y la política de cancelación?». Si necesitas raquetas: «¿Alquilan también equipamiento?». Solicita confirmación por email.",
    "target_vocabulary": ["reservar", "cancha de tenis", "domingo", "disponibilidad", "tarifa", "cancelación", "alquilar", "equipamiento", "horario", "confirmación", "raqueta", "pelotas", "polideportivo", "socio", "pista", "iluminación", "precio", "política", "email", "recordatorio"],
    "user_audio": "mp3 file",
    "created_at": "2025-08-07T12:00:00Z"
  },
  {
    "id": "a3b4c5d6-e7f8-9012-cdef-3456789012ab",
    "session_id": "sess_2025_013",
    "user_id": "user_123",
    "title": "Telling the delivery driver he is at the wrong building number",
    "role_scenario": "You meet the driver outside and explain he is at building 54 instead of your building 45.",
    "feedback": "Di «Creo que hay un error; yo vivo en el edificio 45, no en el 54». Señala visualmente: «Es el de la esquina con el kiosco rojo». Si necesita dar la vuelta: «Gire aquí y es el segundo portal». Agradece su tiempo: «Gracias por la molestia».",
    "target_vocabulary": ["equivocado", "edificio", "número", "cuarenta y cinco", "cincuenta y cuatro", "portal", "kiosco", "vuelta", "señal", "conducir", "error", "callejón", "molestia", "entrega", "paquete", "dirección", "esquina", "señalar", "gracias", "corregir"],
    "user_audio": "mp3 file",
    "created_at": "2025-08-07T12:15:00Z"
  },
  {
    "id": "b4c5d6e7-f8a9-0123-defa-4567890123bc",
    "session_id": "sess_2025_014",
    "user_id": "user_123",
    "title": "Asking a friend to pet-sit your cat for three days",
    "role_scenario": "You ask a good friend to look after your cat for three days while you visit family out of town.",
    "feedback": "«¿Podrías cuidar a mi gato tres días mientras visito a mi familia?» es claro. Detalla horarios: «Una comida al día y una limpieza diaria». Entrega llaves y contacto del veterinario: «Aquí tienes mi llave y el teléfono del vet, por si acaso». Ofrece retribución: «Te invito a cenar cuando vuelva».",
    "target_vocabulary": ["cuidar", "gato", "tres días", "visitar", "familia", "alimentación", "llaves", "veterinario", "retribución", "cena", "contacto", "vacaciones", "mascota", "instrucciones", "arenero", "comida", "agua", "emergencia", "confianza", "amigo"],
    "user_audio": "mp3 file",
    "created_at": "2025-08-07T12:30:00Z"
  },
  {
    "id": "c5d6e7f8-a9b0-1234-efab-5678901234cd",
    "session_id": "sess_2025_015",
    "user_id": "user_123",
    "title": "Calling roadside assistance for a flat tire on the highway",
    "role_scenario": "You are stuck on the highway with a flat tire and call roadside assistance because you don’t know how to change it.",
    "feedback": "«Tengo un pinchazo en la autopista y no sé cómo cambiarlo» es perfecto. Añade ubicación exacta: «Estoy en el kilómetro 142 dirección Valencia». Describe el coche: «Seat León gris, matrícula 1234 BCD». Pregunta por el tiempo de llegada: «¿Cuánto tardan?». Si tienes niños, menciónalo.",
    "target_vocabulary": ["pinchazo", "autopista", "cambiar", "neumático", "asistencia", "kilómetro", "matrícula", "llegada", "herramientas", "gato", "rueda", "seguridad", "carretera", "vehículo", "emergencia", "espera", "grúa", "mecánico", "triángulo", "chaleco"],
    "user_audio": "mp3 file",
    "created_at": "2025-08-07T12:45:00Z"
  },
  {
    "id": "d6e7f8a9-b0c1-2345-fabc-6789012345de",
    "session_id": "sess_2025_016",
    "user_id": "user_123",
    "title": "Calling the clinic to check if last week's blood test results are ready",
    "role_scenario": "You ring the clinic to ask whether your blood test results from last week are available.",
    "feedback": "«¿Ya están listos los resultados del análisis de sangre de la semana pasada?» es neutro. Facilita tus datos: «Soy Marta López, DNI 12345678A». Pregunta si necesitan cita para entregarlos: «¿Debo pasar o me los pueden enviar por email?». Agradece.",
    "target_vocabulary": ["resultados", "análisis de sangre", "listos", "semana pasada", "DNI", "cita", "email", "clínica", "informe", "médico", "paciente", "muestra", "laboratorio", "disponible", "entrega", "recepción", "confidencialidad", "gracias", "consulta", "salud"],
    "user_audio": "mp3 file",
    "created_at": "2025-08-07T13:00:00Z"
  },
  {
    "id": "e7f8a9b0-c1d2-3456-abcd-7890123456ef",
    "session_id": "sess_2025_017",
    "user_id": "user_123",
    "title": "Returning expired milk to the supermarket",
    "role_scenario": "You go back to the supermarket with the receipt because the milk you bought yesterday expired last week.",
    "feedback": "«Compré esta leche ayer y veo que venció la semana pasada» es claro. Muestra el recibo: «Aquí tengo el ticket». Solicita cambio o devolución: «¿Podría cambiarla o devolverme el dinero?». Si compraste más productos, revisa las fechas.",
    "target_vocabulary": ["vencido", "leche", "recibo", "cambiar", "ayer", "caducidad", "ticket", "supermercado", "producto", "devolución", "reembolso", "fecha", "nevera", "daño", "consumo", "calidad", "inspección", "política", "cliente", "insatisfacción"],
    "user_audio": "mp3 file",
    "created_at": "2025-08-07T13:15:00Z"
  },
  {
    "id": "f8a9b0c1-d2e3-4567-bcde-8901234567fa",
    "session_id": "sess_2025_018",
    "user_id": "user_123",
    "title": "Emailing Amazon about a package marked delivered but never received",
    "role_scenario": "You write to Amazon customer service because the tracking says delivered but you did not get the package.",
    "feedback": "Usa tono formal: «El seguimiento indica entregado, pero no lo recibí». Proporciona número de pedido y dirección. Pregunta por investigación: «¿Podrían revisar con el repartidor?». Solicita reenvío o reembolso.",
    "target_vocabulary": ["paquete", "seguimiento", "entregado", "recibir", "revisar", "pedido", "dirección", "investigación", "repatriador", "compensación", "reeenvío", "reembolso", "cliente", "servicio", "evidencia", "foto", "puerta", "vecino", "reclamación", "solución"],
    "user_audio": "mp3 file",
    "created_at": "2025-08-07T13:30:00Z"
  },
  {
    "id": "a9b0c1d2-e3f4-5678-cdef-9012345678ab",
    "session_id": "sess_2025_019",
    "user_id": "user_123",
    "title": "Telling the barber he cut your hair shorter than requested",
    "role_scenario": "You show the barber a photo of the style you wanted and explain he went shorter than you asked.",
    "feedback": "«Me lo ha dejado más corto de lo que quería» es correcto. Muestra la foto: «Este es el estilo que tenía en mente». Pregunta opciones: «¿Podemos corregirlo sin raparme?». Sé constructivo.",
    "target_vocabulary": ["más corto", "estilo", "arreglar", "foto", "barbero", "rapar", "corregir", "longitud", "tijeras", "degradado", "largo", "referencia", "imagen", "confianza", "insatisfacción", "solución", "ajuste", "corte", "peinado", "cliente"],
    "user_audio": "mp3 file",
    "created_at": "2025-08-07T13:45:00Z"
  },
  {
    "id": "b0c1d2e3-f4a5-6789-defa-0123456789bc",
    "session_id": "sess_2025_020",
    "user_id": "user_123",
    "title": "Giving the best-man toast in Spanish at a wedding",
    "role_scenario": "At the wedding you, as best man, need to deliver a short toast in Spanish to the couple.",
    "feedback": "Empieza: «Queridos amigos y familia, queremos brindar por esta hermosa pareja». Usa «por» no «para». Añade deseos: «Les deseo felicidad, amor y muchas risas compartidas». Manténlo breve y emocional.",
    "target_vocabulary": ["brindis", "pareja", "felicidad", "queridos", "esposos", "amor", "familia", "risas", "compartidas", "emoción", "boda", "celebración", "discurso", "hermosa", "unión", "vida", "matrimonio", "recuerdos", "futuro", "salud"],
    "user_audio": "mp3 file",
    "created_at": "2025-08-07T14:00:00Z"
  },
  {
    "id": "c1d2e3f4-a5b6-7890-abcd-1234567890cd",
    "session_id": "sess_2025_021",
    "user_id": "user_123",
    "title": "Reporting to the city that a neighbor never picks up dog poop",
    "role_scenario": "You call the city hotline to report that your neighbor never cleans up dog excrement in front of your door.",
    "feedback": "Usa formalidad: «Quiero reportar que un vecino nunca recoge los excrementos de su perro frente a mi puerta». Da dirección exacta y frecuencia: «Es a diario». Solicita patrullaje o multa.",
    "target_vocabulary": ["excrementos", "recoger", "vecino", "frente", "queja", "patrullaje", "multa", "frecuencia", "dirección", "suciedad", "ordenanza", "salubridad", "responsabilidad", "propietario", "perro", "denuncia", "servicio", "limpieza", "infracción", "evidencia"],
    "user_audio": "mp3 file",
    "created_at": "2025-08-07T14:15:00Z"
  },
  {
    "id": "d2e3f4a5-b6c7-8901-bcde-2345678901de",
    "session_id": "sess_2025_022",
    "user_id": "user_123",
    "title": "Texting the landlord that rent will be five days late due to delayed salary",
    "role_scenario": "You message the landlord that your salary was delayed so rent will arrive five days late.",
    "feedback": "«Disculpe, mi salario se retrasó; el alquiler llegará cinco días tarde» es claro. Propón fecha concreta: «El martes 15 a más tardar». Ofrece compensación: «Puedo abonar intereses si lo considera».",
    "target_vocabulary": ["alquiler", "retrasado", "salario", "cinco días", "disculpa", "compensación", "fecha", "intereses", "puntualidad", "comunicación", "justificación", "acuerdo", "compromiso", "efectivo", "transferencia", "mora", "propietario", "arrendatario", "entendimiento", "solvente"],
    "user_audio": "mp3 file",
    "created_at": "2025-08-07T14:30:00Z"
  },
  {
    "id": "e3f4a5b6-c7d8-9012-cdef-3456789012ef",
    "session_id": "sess_2025_023",
    "user_id": "user_123",
    "title": "Emailing a client to reschedule Tuesday 3 pm meeting to Friday",
    "role_scenario": "You email the client to move the Tuesday 3 pm meeting to Friday same time due to a doctor appointment.",
    "feedback": "«Por motivos médicos, necesito reprogramar nuestra reunión del martes a las 15:00 al viernes a la misma hora» es conciso. Ofrece alternativas: «Si viernes no le conviene, tengo flexibilidad el jueves tarde».",
    "target_vocabulary": ["reprogramar", "reunión", "martes", "viernes", "cita médica", "flexibilidad", "cliente", "alternativa", "horario", "motivos", "médicos", "disponibilidad", "disculpa", "agenda", "compromiso", "posponer", "confirmar", "calendar", "eficiencia", "colaboración"],
    "user_audio": "mp3 file",
    "created_at": "2025-08-07T14:45:00Z"
  },
  {
    "id": "f4a5b6c7-d8e9-0123-defa-4567890123fa",
    "session_id": "sess_2025_024",
    "user_id": "user_123",
    "title": "Calling building maintenance about no hot water since morning",
    "role_scenario": "You call maintenance because there has been no hot water in your apartment since this morning.",
    "feedback": "«Desde esta mañana no hay agua caliente en mi apartamento» es directo. Añade síntomas: «Sale fría incluso dejando correr». Pregunta por causa: «¿Es avería general o solo mi piso?». Ofrece acceso: «Estoy en casa hasta las 6».",
    "target_vocabulary": ["agua caliente", "mañana", "revisar", "mantenimiento", "apartamento", "avería", "causa", "acceso", "boiler", "calefón", "fontanería", "urgencia", "fría", "piso", "general", "reparador", "horario", "llave", "ingreso", "gracias"],
    "user_audio": "mp3 file",
    "created_at": "2025-08-07T15:00:00Z"
  },
  {
    "id": "a5b6c7d8-e9f0-1234-efab-5678901234ab",
    "session_id": "sess_2025_025",
    "user_id": "user_123",
    "title": "Asking a classmate to send presentation slides after laptop crash",
    "role_scenario": "Your laptop crashed and you need your classmate to send the group-project slides.",
    "feedback": "«Mi computadora se estropeó, ¿podrías enviarme las diapositivas?» es claro. Especifica formato: «Prefiero PDF y PPT». Añade plazo: «Necesito imprimirlas para mañana». Agradece ofreciendo café.",
    "target_vocabulary": ["diapositivas", "enviar", "computadora", "estropearse", "trabajo", "formato", "PDF", "PPT", "impresión", "plazo", "problema técnico", "copia", "USB", "nube", "compañero", "grupo", "presentación", "urgencia", "backup", "apoyo"],
    "user_audio": "mp3 file",
    "created_at": "2025-08-07T15:15:00Z"
  },
  {
    "id": "b6c7d8e9-f0a1-2345-fabc-6789012345bc",
    "session_id": "sess_2025_026",
    "user_id": "user_123",
    "title": "Asking siblings in group chat what to buy Mom for her 60th birthday",
    "role_scenario": "You message your brothers and sisters to decide together on a gift for Mom’s upcoming 60th birthday.",
    "feedback": "«Se acerca el cumple de mamá, cumple 60 años. ¿Qué le regalamos?» es cercano. Propón ideas: «¿Una cena, una escapada, algo personalizado?». Crea encuesta rápida: «Pondré opciones con precios».",
    "target_vocabulary": ["regalo", "cumpleaños", "hermanos", "mes que viene", "madre", "60 años", "cena", "escapada", "personalizado", "encuesta", "precio", "ideas", "recordatorio", "familia", "celebrar", "sorpresa", "opciones", "votar", "presupuesto", "consenso"],
    "user_audio": "mp3 file",
    "created_at": "2025-08-07T15:30:00Z"
  },
  {
    "id": "c7d8e9f0-a1b2-3456-abcd-7890123456cd",
    "session_id": "sess_2025_027",
    "user_id": "user_123",
    "title": "Messaging online shop for full refund on damaged shoes",
    "role_scenario": "You write the e-shop that your shoes arrived damaged and you want a full refund, not an exchange.",
    "feedback": "«Los zapatos llegaron dañados y prefiero un reembolso completo, no un cambio». Adjunta fotos del daño y número de pedido. Pregunta por devolución gratuita: «¿Envían etiqueta de devolución?»",
    "target_vocabulary": ["dañado", "reembolso", "completo", "zapatos", "devolución", "etiqueta", "daños", "foto", "gastos", "cliente", "garantía", "transporte", "paquete", "inspección", "calidad", "insatisfacción", "solución", "prueba", "envío", "gestión"],
    "user_audio": "mp3 file",
    "created_at": "2025-08-07T15:45:00Z"
  },
  {
    "id": "d8e9f0a1-b2c3-4567-bcde-8901234567de",
    "session_id": "sess_2025_028",
    "user_id": "user_123",
    "title": "Texting mom to pick up kids from school because of traffic",
    "role_scenario": "You are stuck in traffic and text your mom to collect the kids from school today.",
    "feedback": "«Estoy atascado en el tráfico, ¿podrías recoger a los niños hoy?» Añade horario y lugar: «Salen a las 15:30 por la puerta principal». Avisa si hay cambio de planes.",
    "target_vocabulary": ["recoger", "niños", "atascado", "tráfico", "hoy", "puerta principal", "salida", "cambio", "aviso", "abuela", "escuela", "apuro", "tiempo", "espera", "conductor", "ruta", "mensaje", "confirmar", "gracias", "ayuda"],
    "user_audio": "mp3 file",
    "created_at": "2025-08-07T16:00:00Z"
  },
  {
    "id": "e9f0a1b2-c3d4-5678-cdef-9012345678ef",
    "session_id": "sess_2025_029",
    "user_id": "user_123",
    "title": "Asking hotel reception to change rooms due to street noise",
    "role_scenario": "You complain that your room faces the street and is too loud to sleep, requesting a quieter room.",
    "feedback": "«Mi habitación da a la calle y está demasiado ruidosa para dormir, ¿podría cambiar de habitación?». Pregunta por disponibilidad interior y ofrece esperar si es necesario.",
    "target_vocabulary": ["ruidoso", "calle", "cambiar", "habitación", "dormir", "disponibilidad", "interior", "ruido", "descanso", "recepción", "molestia", "solución", "alternativa", "silencio", "comodidad", "huésped", "insomnio", "tranquilidad", "espera", "gracias"],
    "user_audio": "mp3 file",
    "created_at": "2025-08-07T16:15:00Z"
  },
  {
    "id": "f0a1b2c3-d4e5-6789-defa-0123456789fa",
    "session_id": "sess_2025_030",
    "user_id": "user_123",
    "title": "Asking friend when he can pay back €200 lent last month",
    "role_scenario": "You lent your friend €200 last month and now ask when he can return the money.",
    "feedback": "«¿Cuándo podrías devolverme los doscientos euros que te presté el mes pasado?» es directo. Ofrece flexibilidad: «Si necesitas más tiempo, dime y vemos plazos».",
    "target_vocabulary": ["devolver", "prestar", "doscientos", "mes pasado", "dinero", "plazo", "flexibilidad", "deuda", "acuerdo", "pago", "amigo", "confianza", "necesidad", "devolución", "cuota", "transferencia", "efectivo", "compromiso", "entendimiento", "gracias"],
    "user_audio": "mp3 file",
    "created_at": "2025-08-07T16:30:00Z"
  },
  {
    "id": "a1b2c3d4-e5f6-7890-abcd-1234567890ab",
    "session_id": "sess_2025_031",
    "user_id": "user_123",
    "title": "Calling dry cleaner after they lost your white shirt needed for a wedding",
    "role_scenario": "You phone the dry cleaner because they lost your white shirt you dropped off last week and you need it for a wedding.",
    "feedback": "«Perdieron mi camisa blanca que dejé la semana pasada y la necesito para una boda». Pide solución inmediata: «¿Tienen algo similar o pueden reembolsarme?». Solicita seguimiento.",
    "target_vocabulary": ["camisa", "perdido", "lavandería", "boda", "semana pasada", "reembolso", "solución", "seguimiento", "urgente", "vestimenta", "formal", "sustituto", "daños", "responsabilidad", "recibo", "ticket", "cliente", "compensación", "inspección", "especial"],
    "user_audio": "mp3 file",
    "created_at": "2025-08-07T16:45:00Z"
  },
  {
    "id": "b2c3d4e5-f6a7-8901-bcde-2345678901bc",
    "session_id": "sess_2025_032",
    "user_id": "user_123",
    "title": "Telling your English student you must stop private lessons due to full-time job",
    "role_scenario": "You inform your private English student you can’t continue lessons because you accepted a full-time job.",
    "feedback": "«Lamento informarte que debo dejar las clases por mi nuevo trabajo a tiempo completo». Agradece su comprensión y ofrece recomendación de otro profesor.",
    "target_vocabulary": ["dejar", "clases", "trabajo completo", "entender", "gracias", "recomendación", "profesor", "estudiante", "comprensión", "transición", "horario", "compromiso", "agradecimiento", "oportunidad", "futuro", "continuidad", "contacto", "red", "apoyo", "despedida"],
    "user_audio": "mp3 file",
    "created_at": "2025-08-07T17:00:00Z"
  },
  {
    "id": "c3d4e5f6-a7b8-9012-cdef-3456789012cd",
    "session_id": "sess_2025_033",
    "user_id": "user_123",
    "title": "Calling embassy to report lost passport at metro station",
    "role_scenario": "You lost your passport at the metro station this morning and call the embassy to report it.",
    "feedback": "«Perdí mi pasaporte esta mañana en la estación de metro». Proporciona nacionalidad, número y contacto. Pregunta por pasos para duplicado urgente.",
    "target_vocabulary": ["pasaporte", "perder", "embajada", "metro", "mañana", "duplicado", "urgente", "nacionalidad", "oficina", "contacto", "formulario", "trámite", "identidad", "documento", "cita", "fotografía", "tasa", "legalización", "consulado", "protección"],
    "user_audio": "mp3 file",
    "created_at": "2025-08-07T17:15:00Z"
  },
  {
    "id": "d4e5f6a7-b8c9-0123-defa-4567890123de",
    "session_id": "sess_2025_034",
    "user_id": "user_123",
    "title": "Asking girlfriend’s best friend to help plan surprise proposal at restaurant",
    "role_scenario": "You ask your girlfriend’s best friend to help you plan a surprise proposal at a restaurant next Friday.",
    "feedback": "«¿Me ayudas a planear una propuesta sorpresa el próximo viernes en el restaurante?». Pide ideas y coordinación con el personal del lugar.",
    "target_vocabulary": ["propuesta", "sorpresa", "restaurante", "viernes", "ayudar", "planear", "coordinación", "anillo", "flores", "música", "cena", "romántico", "amiga", "ilusión", "secreto", "detalles", "servicio", "mesa", "brindis", "fotografía"],
    "user_audio": "mp3 file",
    "created_at": "2025-08-07T17:30:00Z"
  },
  {
    "id": "e5f6a7b8-c9d0-1234-efab-5678901234ef",
    "session_id": "sess_2025_035",
    "user_id": "user_123",
    "title": "Telling coworker not to spoil the new movie you haven't watched",
    "role_scenario": "You tell a coworker not to reveal spoilers because you haven’t seen the new movie yet.",
    "feedback": "«No me lo arruines, aún no he visto la nueva película» es natural y amigable.",
    "target_vocabulary": ["arruinar", "película", "aún no", "espoiler", "colega", "trama", "final", "sorpresa", "estreno", "cine", "suspenso", "revelación", "placer", "discusión", "secretismo", "cultura pop", "afición", "silencio", "respeto", "experiencia"],
    "user_audio": "mp3 file",
    "created_at": "2025-08-07T17:45:00Z"
  },
  {
    "id": "f6a7b8c9-d0e1-2345-fabc-6789012345fa",
    "session_id": "sess_2025_036",
    "user_id": "user_123",
    "title": "Calling bus company to refund ticket after positive COVID test",
    "role_scenario": "You tested positive for COVID and call the bus company to refund your ticket.",
    "feedback": "«Di positivo en COVID y no puedo viajar; solicito reembolso del billete». Adjunte prueba médica si es necesario.",
    "target_vocabulary": ["covid", "positivo", "reembolso", "viaje", "autobús", "prueba médica", "boleto", "cancelación", "salud", "aislamiento", "síntomas", "política", "garantía", "formulario", "documento", "devolución", "asistencia", "prevención", "emergencia", "comprensión"],
    "user_audio": "mp3 file",
    "created_at": "2025-08-07T18:00:00Z"
  },
  {
    "id": "a7b8c9d0-e1f2-3456-abcd-7890123456ab",
    "session_id": "sess_2025_037",
    "user_id": "user_123",
    "title": "Calling pizzeria to replace wrong order",
    "role_scenario": "They delivered pepperoni but you ordered vegetarian; you call for a replacement.",
    "feedback": "«Me enviaron una pizza equivocada; pedí vegetariana y trajeron pepperoni. ¿Podrían cambiarla?». Ofrece devolver la incorrecta.",
    "target_vocabulary": ["equivocada", "vegetariana", "cambiar", "pizzería", "pepperoni", "entrega", "repartidor", "recibo", "devolución", "gusto", "error", "sabor", "ingredientes", "cliente", "servicio", "rápido", "solución", "hambre", "espera", "compensación"],
    "user_audio": "mp3 file",
    "created_at": "2025-08-07T18:15:00Z"
  },
  {
    "id": "b8c9d0e1-f2a3-4567-bcde-8901234567bc",
    "session_id": "sess_2025_038",
    "user_id": "user_123",
    "title": "Calling dentist to reschedule tomorrow due to work trip",
    "role_scenario": "You need to move tomorrow’s dentist appointment to next week because of a business trip.",
    "feedback": "«Necesito cambiar mi cita de mañana por un viaje de trabajo. ¿Tienen disponibilidad la semana que viene?» Propón dos franjas.",
    "target_vocabulary": ["cambiar", "cita", "viaje", "trabajo", "semana", "disponibilidad", "franja", "horario", "consulta", "reprogramar", "urgencia", "confirmación", "gracias", "comprensión", "agenda", "odontólogo", "tratamiento", "flexibilidad", "calendario", "seguro"],
    "user_audio": "mp3 file",
    "created_at": "2025-08-07T18:30:00Z"
  },
  {
    "id": "c9d0e1f2-a3b4-5678-cdef-9012345678cd",
    "session_id": "sess_2025_039",
    "user_id": "user_123",
    "title": "Inviting neighbors to housewarming party",
    "role_scenario": "You knock on the neighbors’ doors to invite them to your housewarming party this Saturday at 7 pm.",
    "feedback": "«Hola, este sábado a las siete celebramos una fiesta de inauguración. ¡Esperamos que puedan venir!» Entrega dirección y pide confirmación.",
    "target_vocabulary": ["inauguración", "sábado", "invitar", "vecinos", "esperar", "fiesta", "casa", "confirmación", "celebración", "puerta", "copa", "snacks", "bienvenida", "comunidad", "relaciones", "charla", "musica", "brindis", "alegría", "presencia"],
    "user_audio": "mp3 file",
    "created_at": "2025-08-07T18:45:00Z"
  },
  {
    "id": "d0e1f2a3-b4c5-6789-defa-0123456789de",
    "session_id": "sess_2025_040",
    "user_id": "user_123",
    "title": "Asking boss for salary increase after 18 months at company",
    "role_scenario": "You schedule a meeting to request a raise after 18 months with the firm.",
    "feedback": "«Quisiera agendar una reunión para hablar sobre un posible aumento salarial tras dieciocho meses en la empresa». Enumera logros.",
    "target_vocabulary": ["aumento", "reunión", "salario", "meses", "empresa", "logros", "méritos", "evaluación", "productividad", "compromiso", "reconocimiento", "responsabilidad", "trayectoria", "compensación", "negociación", "plan", "objetivos", "métricas", "satisfacción", "retención"],
    "user_audio": "mp3 file",
    "created_at": "2025-08-07T19:00:00Z"
  },
  {
    "id": "e1f2a3b4-c5d6-7890-abcd-1234567890ef",
    "session_id": "sess_2025_041",
    "user_id": "user_123",
    "title": "Asking gate agent if hotel is provided for 3-hour flight delay",
    "role_scenario": "Announcement says your flight is delayed three hours; you ask the gate agent about hotel accommodation.",
    "feedback": "«El vuelo está retrasado tres horas. ¿Proporcionan hotel o vales de comida?» Pregunta por derechos.",
    "target_vocabulary": ["retrasado", "hotel", "proporcionar", "agente", "horas", "vale", "comida", "derechos", "pasajero", "compensación", "comodidad", "espera", "aeropuerto", "instalaciones", "gratis", "cama", "transporte", "información", "cliente", "gestión"],
    "user_audio": "mp3 file",
    "created_at": "2025-08-07T19:15:00Z"
  },
  {
    "id": "f2a3b4c5-d6e7-8901-bcde-2345678901fa",
    "session_id": "sess_2025_042",
    "user_id": "user_123",
    "title": "Applying for small bank loan to buy used car",
    "role_scenario": "You visit the bank to request a small loan for a second-hand car, explaining you have a stable job.",
    "feedback": "«Solicito un préstamo pequeño para un coche de segunda mano; tengo trabajo estable y nómina fija». Presenta documentación.",
    "target_vocabulary": ["préstamo", "coche", "segunda mano", "trabajo", "estable", "nómina", "banco", "interés", "cuota", "aval", "documentación", "solicitud", "financiación", "crédito", "ingresos", "garantía", "plazo", "tasa", "compra", "concesión"],
    "user_audio": "mp3 file",
    "created_at": "2025-08-07T19:30:00Z"
  },
  {
    "id": "a3b4c5d6-e7f8-9012-cdef-3456789012ab",
    "session_id": "sess_2025_043",
    "user_id": "user_123",
    "title": "Calling gym to cancel membership after moving city",
    "role_scenario": "You moved to another city and need to terminate your gym membership.",
    "feedback": "«Me mudé a otra ciudad y deseo cancelar la membresía con efecto inmediato». Solicita confirmación por email.",
    "target_vocabulary": ["cancelar", "membresía", "mudanza", "ciudad", "inmediato", "confirmación", "baja", "cliente", "servicio", "suscripción", "dirección", "trámite", "finalización", "política", "aviso", "comprobante", "gracias", "comprensión", "cierre", "documento"],
    "user_audio": "mp3 file",
    "created_at": "2025-08-07T19:45:00Z"
  },
  {
    "id": "b4c5d6e7-f8a9-0123-defa-4567890123bc",
    "session_id": "sess_2025_044",
    "user_id": "user_123",
    "title": "Asking wife’s best friend to help plan surprise anniversary getaway",
    "role_scenario": "You ask your wife’s best friend to help you organize a surprise weekend trip for your anniversary.",
    "feedback": "«¿Me ayudas a planear una escapada de fin de semana sorpresa para nuestro aniversario?». Coordina fechas y preferencias.",
    "target_vocabulary": ["escapada", "aniversario", "sorpresa", "planear", "amiga", "hotel", "romántico", "detalles", "coordinar", "reserva", "conspiración", "celebración", "pareja", "ilusión", "viaje", "intimidad", "gestos", "recuerdos", "amor", "organización"],
    "user_audio": "mp3 file",
    "created_at": "2025-08-07T20:00:00Z"
  },
  {
    "id": "c5d6e7f8-a9b0-1234-efab-5678901234cd",
    "session_id": "sess_2025_045",
    "user_id": "user_123",
    "title": "Reporting inappropriate coworker comments to HR",
    "role_scenario": "You call HR to report a colleague who keeps making inappropriate comments to you.",
    "feedback": "«Quiero reportar a mi compañero por comentarios inapropiados continuos». Proporciona fechas, testigos y ejemplos. Solicita medidas.",
    "target_vocabulary": ["acoso", "inapropiado", "comentarios", "recursos humanos", "reportar", "testigos", "medidas", "documentación", "ambiente laboral", "situación", "protocolo", "investigación", "respeto", "privacidad", "seguridad", "denuncia", "sanción", "formalidad", "soporte", "prevención"],
    "user_audio": "mp3 file",
    "created_at": "2025-08-07T20:15:00Z"
  },
  {
    "id": "d6e7f8a9-b0c1-2345-fabc-6789012345de",
    "session_id": "sess_2025_046",
    "user_id": "user_123",
    "title": "Reminding mom about dentist appointment tomorrow at 10 am",
    "role_scenario": "You call your mom to remind her she has a dentist appointment tomorrow at 10 am.",
    "feedback": "«Recordatorio: mañana a las diez tienes cita con el dentista. No olvides llevar tu tarjeta sanitaria».",
    "target_vocabulary": ["recordatorio", "dentista", "mañana", "diez", "no olvidar", "cita", "tarjeta sanitaria", "confirmación", "mamá", "salud", "hora", "preparación", "transporte", "llamada", "cariño", "asistencia", "prevención", "control", "aviso", "puntualidad"],
    "user_audio": "mp3 file",
    "created_at": "2025-08-07T20:30:00Z"
  },
  {
    "id": "e7f8a9b0-c1d2-3456-abcd-7890123456ef",
    "session_id": "sess_2025_047",
    "user_id": "user_123",
    "title": "Telling delivery driver the order is wrong",
    "role_scenario": "You tell the driver this isn’t your order; you ordered sushi and they brought pizza.",
    "feedback": "«Este no es mi pedido; pedí sushi y trajeron pizza. ¿Podrían traer el correcto?» Muestra confirmación.",
    "target_vocabulary": ["pedido", "equivocado", "sushi", "pizza", "entrega", "confirmación", "repartidor", "cambio", "error", "cliente", "app", "restaurante", "corrección", "espera", "hambre", "solución", "reembolso", "inspección", "verificación", "atención"],
    "user_audio": "mp3 file",
    "created_at": "2025-08-07T20:45:00Z"
  },
  {
    "id": "f8a9b0c1-d2e3-4567-bcde-8901234567fa",
    "session_id": "sess_2025_048",
    "user_id": "user_123",
    "title": "Checking venue availability for 30th birthday party next Saturday 7 pm–12 am",
    "role_scenario": "You email the venue to ask if they are free next Saturday from 7 pm to midnight for a 30th birthday party.",
    "feedback": "«¿Tienen disponibilidad el próximo sábado de 19:00 a 00:00 para celebrar un cumpleaños 30?». Pregunta por tarifas y catering.",
    "target_vocabulary": ["disponibilidad", "cumpleaños", "sábado", "salón", "hora", "tarifa", "catering", "capacidad", "menú", "decoración", "música", "contrato", "reserva", "invitados", "celebración", "evento", "pista", "brindis", "confirmación", "política"],
    "user_audio": "mp3 file",
    "created_at": "2025-08-07T21:00:00Z"
  },
  {
    "id": "a9b0c1d2-e3f4-5678-cdef-9012345678ab",
    "session_id": "sess_2025_049",
    "user_id": "user_123",
    "title": "Asking friend for mock interview practice for sales manager role",
    "role_scenario": "Tomorrow you have an interview for a sales manager position and you ask a friend to run a mock interview with you tonight.",
    "feedback": "«¿Te importaría hacerme una entrevista simulada esta noche para el puesto de gerente de ventas?». Comparte la descripción del trabajo.",
    "target_vocabulary": ["entrevista", "simulada", "gerente", "ventas", "práctica", "preguntas", "competencias", "feedback", "preparación", "currículum", "puesto", "nervios", "confianza", "estrategia", "objetivos", "resultados", "comunicación", "negociación", "liderazgo", "simulación"],
    "user_audio": "mp3 file",
    "created_at": "2025-08-07T21:15:00Z"
  },
  {
    "id": "b0c1d2e3-f4a5-6789-defa-0123456789bc",
    "session_id": "sess_2025_050",
    "user_id": "user_123",
    "title": "Texting date you’re running 20 minutes late due to traffic",
    "role_scenario": "You message your date that you will be 20 minutes late because traffic is heavy.",
    "feedback": "«Llegaré 20 minutos tarde; el tráfico está pesado. Disculpa».",
    "target_vocabulary": ["llegar tarde", "veinte", "tráfico", "pesado", "disculpa", "retraso", "espera", "molestia", "mensaje", "cita", "ruta", "conductor", "tiempo", "paciencia", "comprensión", "aviso", "GPS", "compensación", "sonrisa", "reencuentro"],
    "user_audio": "mp3 file",
    "created_at": "2025-08-07T21:30:00Z"
  }
]



// const userSessions = [{
//   "id": "uuid",
//   "session_id": "unique id from vapi",
//   "user_id": "clerk provider unique user id",
//   "title": "realistic, descriptive, and instantly identifiable description of role_scenario",
//   "role_scenario": "user inputed role scenario",
//   "feedback": "long, natural, teacher-style, mixing the target language and English, including error highlighting, corrections, and cultural insights.",
//   "target_vocabulary": [{
//         "vocab": "the word/phrase in infinitive form", 
//         "part_of_speech": "either the part of speech or type phrase",
//         "meaning": ["english gloss/translation", 
//                     "another translation if it exists and so on"], 
//         "tone": "Formal, Neutral or Casual", 
//         "regional variations": [{
//                   "Country": "e.g Spain", 
//                   "word": "word/phrase", 
//                   "part_of_speech": "either the part of speech or type phrase",
//                   "meaning": ["english gloss/translation", 
//                               "another translation if it exists and so on"], 
//                   "example": {
//                               "sentence": "an example using the word/phrase in spanish", 
//                               "translation": "translation"}
//                             }], 
//         "examples": [{
//                   "sentence": "first example must be from the conversation, where it was used, an example using the word/phrase in spanish", 
//                   "translation": "translation"}], 
//         "idioms": [{"phrase": "idiom using the word", "meaning": "meaning in user's language"}],
//         "synonyms": ["list of synonyms"], 
//         "antonyms":  ["list of antonyms"],
//       },],
//   "user_audio": "https://example.com/audio/pedir_practice.mp3",
//   "created_at": "timestamp"
// }]

