export const userSessions = [
  {
    id: "a1b2c3d4-e5f6-7890-abcd-1234567890ab",
    session_id: "sess_2025_001",
    user_id: "user_123",
    title: "Ask girl on date",
    role_scenario: "you see a girl at the library every day and want to ask her to get coffee this weekend",
    feedback: "- **Would you like** → *Te gustaría* not *quieres*\n- **This weekend** → *este fin de semana* not *este weekend*\n- **Get coffee** → *tomar un café* not *coger*\n- You said *con migo*; correct *conmigo*",
    target_vocabulary: ["te gustaría", "tomar un café", "este fin de semana", "conmigo", "biblioteca"],
    user_audio: "mp3 file",
    created_at: "2025-08-07T09:15:00Z"
  },
  {
    id: "b2c3d4e5-f6a7-8901-bcde-2345678901bc",
    session_id: "sess_2025_002",
    user_id: "user_123",
    title: "Ask boss for raise",
    role_scenario: "you've worked at the company for 2 yrs and want 10 percent raise meeting with your manager",
    feedback: "- **I’d like to discuss** → *Me gustaría hablar*\n- **Two years** → *dos años* not *2 años*\n- **10 percent raise** → *un aumento del diez por ciento*\n- You used *subida*; better *aumento* in formal context",
    target_vocabulary: ["aumento", "discutir", "desempeño", "salario", "reconocimiento"],
    user_audio: "mp3 file",
    created_at: "2025-08-07T09:30:00Z"
  },
  {
    id: "c3d4e5f6-a7b8-9012-cdef-3456789012cd",
    session_id: "sess_2025_003",
    user_id: "user_123",
    title: "Surprise party plan",
    role_scenario: "call your wifes sister to plan surprise 30th bday party without wife knowing",
    feedback: "- **Without her knowing** → *sin que se entere*\n- **30th birthday** → *su trigésimo cumpleaños*\n- **Can we meet?** → *¿Podemos quedar?*\n- You said *sin ella sabe*; subjunctive needed",
    target_vocabulary: ["sorpresa", "cumpleaños", "sin que se entere", "quedar", "hermana"],
    user_audio: "mp3 file",
    created_at: "2025-08-07T09:45:00Z"
  },
  {
    id: "d4e5f6a7-b8c9-0123-defa-4567890123de",
    session_id: "sess_2025_004",
    user_id: "user_123",
    title: "Dentist reschedule",
    role_scenario: "call dentist office to move tomorrow appointment to next week due to work trip",
    feedback: "- **I need to reschedule** → *Necesito cambiar la cita*\n- **Work trip** → *viaje de trabajo*\n- **Next week** → *la semana que viene*\n- You forgot to specify morning/afternoon",
    target_vocabulary: ["cambiar cita", "viaje de trabajo", "semana que viene"],
    user_audio: "mp3 file",
    created_at: "2025-08-07T10:00:00Z"
  },
  {
    id: "e5f6a7b8-c9d0-1234-efab-5678901234ef",
    session_id: "sess_2025_005",
    user_id: "user_123",
    title: "Return headphones",
    role_scenario: "go back to store bc the headphones you bought yesterday are broken left side no sound",
    feedback: "- **Stopped working** → *dejaron de funcionar*\n- **Left side** → *el lado izquierdo*\n- **Can I return?** → *¿Puedo devolverlos?*\n- You said *no suena*; better *no hay sonido*",
    target_vocabulary: ["devolver", "garantía", "lado izquierdo", "dejar de funcionar"],
    user_audio: "mp3 file",
    created_at: "2025-08-07T10:15:00Z"
  },
  {
    id: "f6a7b8c9-d0e1-2345-fabc-6789012345fa",
    session_id: "sess_2025_006",
    user_id: "user_123",
    title: "Invite coworkers",
    role_scenario: "ask 3 coworkers to your house for bbq this saturday and tell them to bring drinks",
    feedback: "- **We're having a BBQ** → *vamos a hacer una barbacoa*\n- **This Saturday** → *este sábado*\n- **Bring drinks** → *traigan bebidas*\n- You used *lleven*; *traigan* is better for coming",
    target_vocabulary: ["barbacoa", "traer", "bebidas", "sábado", "casa"],
    user_audio: "mp3 file",
    created_at: "2025-08-07T10:30:00Z"
  },
  {
    id: "a7b8c9d0-e1f2-3456-abcd-7890123456ab",
    session_id: "sess_2025_007",
    user_id: "user_123",
    title: "Landlord leak",
    role_scenario: "text landlord that your bathroom ceiling is leaking water since last night",
    feedback: "- **Ceiling is leaking** → *el techo está goteando*\n- **Since last night** → *desde anoche*\n- **Can you fix it?** → *¿Puede arreglarlo?*\n- You forgot to mention urgency *es urgente*",
    target_vocabulary: ["techo", "goteando", "baño", "urgente", "arreglar"],
    user_audio: "mp3 file",
    created_at: "2025-08-07T10:45:00Z"
  },
  {
    id: "b8c9d0e1-f2a3-4567-bcde-8901234567bc",
    session_id: "sess_2025_008",
    user_id: "user_123",
    title: "Borrow charger",
    role_scenario: "ask neighbor if you can borrow phone charger till tomorrow yours broke",
    feedback: "- **Can I borrow** → *¿Puedo prestar* (incorrect) → *¿Puedes prestarme?*\n- **Until tomorrow** → *hasta mañana*\n- **Mine broke** → *el mío se rompió*\n- You said *prestar* wrong direction",
    target_vocabulary: ["prestar", "hasta mañana", "cargador", "romperse"],
    user_audio: "mp3 file",
    created_at: "2025-08-07T11:00:00Z"
  },
  {
    id: "c9d0e1f2-a3b4-5678-cdef-9012345678cd",
    session_id: "sess_2025_009",
    user_id: "user_123",
    title: "Cancel gym",
    role_scenario: "call gym to cancel membership because you moved to another city",
    feedback: "- **I moved** → *Me mudé* not *yo moví*\n- **Another city** → *otra ciudad*\n- **Cancel membership** → *cancelar la membresía*\n- You said *stop gym*; use *cancelar*",
    target_vocabulary: ["mudarse", "cancelar", "membresía", "otra ciudad"],
    user_audio: "mp3 file",
    created_at: "2025-08-07T11:15:00Z"
  },
  {
    id: "d0e1f2a3-b4c5-6789-defa-0123456789de",
    session_id: "sess_2025_010",
    user_id: "user_123",
    title: "Report stolen bike",
    role_scenario: "at police station explain your bike was stolen outside supermarket 2 hours ago",
    feedback: "- **Was stolen** → *me robaron la bicicleta*\n- **Two hours ago** → *hace dos horas*\n- **Outside supermarket** → *frente al supermercado*\n- You used *mi bicicleta fue robada* (passive); active is more natural",
    target_vocabulary: ["robar", "bicicleta", "hace dos horas", "supermercado", "policía"],
    user_audio: "mp3 file",
    created_at: "2025-08-07T11:30:00Z"
  },
  {
    id: "e1f2a3b4-c5d6-7890-abcd-1234567890ef",
    session_id: "sess_2025_011",
    user_id: "user_123",
    title: "Daughter sick",
    role_scenario: "call school to tell them your 8 year old daughter has fever and won't come today",
    feedback: "- **Has a fever** → *tiene fiebre*\n- **Won’t come today** → *no vendrá hoy*\n- **Eight years old** → *ocho años*\n- You said *mi hija es enferma*; use *está enferma*",
    target_vocabulary: ["fiebre", "hija", "no vendrá", "hoy"],
    user_audio: "mp3 file",
    created_at: "2025-08-07T11:45:00Z"
  },
  {
    id: "f2a3b4c5-d6e7-8901-bcde-2345678901fa",
    session_id: "sess_2025_012",
    user_id: "user_123",
    title: "Book tennis court",
    role_scenario: "call sports center to book tennis court for sunday 5pm for 2 hours",
    feedback: "- **I’d like to book** → *Quisiera reservar*\n- **Sunday at 5pm** → *el domingo a las cinco*\n- **For two hours** → *por dos horas*\n- You forgot to ask about availability",
    target_vocabulary: ["reservar", "cancha de tenis", "domingo", "disponibilidad"],
    user_audio: "mp3 file",
    created_at: "2025-08-07T12:00:00Z"
  },
  {
    id: "a3b4c5d6-e7f8-9012-cdef-3456789012ab",
    session_id: "sess_2025_013",
    user_id: "user_123",
    title: "Wrong address",
    role_scenario: "tell food delivery guy he went to wrong building number yours is 45 not 54",
    feedback: "- **Wrong building** → *edificio equivocado*\n- **I’m number 45** → *yo soy el 45*\n- **Not 54** → *no el 54*\n- You said *casa incorrecta*; *edificio* is clearer",
    target_vocabulary: ["equivocado", "edificio", "número", "cuarenta y cinco"],
    user_audio: "mp3 file",
    created_at: "2025-08-07T12:15:00Z"
  },
  {
    id: "b4c5d6e7-f8a9-0123-defa-4567890123bc",
    session_id: "sess_2025_014",
    user_id: "user_123",
    title: "Pet sitter",
    role_scenario: "ask friend to watch your cat for 3 days while you visit family",
    feedback: "- **Can you watch my cat** → *¿Puedes cuidar a mi gato?*\n- **For three days** → *por tres días*\n- **Visit family** → *visitar a mi familia*\n- You used *ver mi gato*; *cuidar* is better",
    target_vocabulary: ["cuidar", "gato", "tres días", "visitar", "familia"],
    user_audio: "mp3 file",
    created_at: "2025-08-07T12:30:00Z"
  },
  {
    id: "c5d6e7f8-a9b0-1234-efab-5678901234cd",
    session_id: "sess_2025_015",
    user_id: "user_123",
    title: "Flat tire",
    role_scenario: "call roadside assistance because you have flat tire on highway don't know how to change",
    feedback: "- **I have a flat tire** → *tengo un pinchazo*\n- **On the highway** → *en la autopista*\n- **I don’t know how** → *no sé cómo cambiarlo*\n- You said *llanta rota*; *pinchazo* is common",
    target_vocabulary: ["pinchazo", "autopista", "cambiar", "neumático", "asistencia"],
    user_audio: "mp3 file",
    created_at: "2025-08-07T12:45:00Z"
  },
  {
    id: "d6e7f8a9-b0c1-2345-fabc-6789012345de",
    session_id: "sess_2025_016",
    user_id: "user_123",
    title: "Doctor results",
    role_scenario: "call clinic to ask if blood test results are ready from last week",
    feedback: "- **Are the results ready?** → *¿Están listos los resultados?*\n- **From last week** → *de la semana pasada*\n- **Blood test** → *análisis de sangre*\n- You used *examen de sangre*; *análisis* is standard",
    target_vocabulary: ["resultados", "análisis de sangre", "listos", "semana pasada"],
    user_audio: "mp3 file",
    created_at: "2025-08-07T13:00:00Z"
  },
  {
    id: "e7f8a9b0-c1d2-3456-abcd-7890123456ef",
    session_id: "sess_2025_017",
    user_id: "user_123",
    title: "Milk expired",
    role_scenario: "go back to supermarket with receipt because milk you bought yesterday expired last week",
    feedback: "- **Expired last week** → *venció la semana pasada*\n- **Yesterday I bought** → *ayer compré*\n- **Can I exchange?** → *¿Puedo cambiarlo?*\n- You said *leche es vieja*; use *vencida*",
    target_vocabulary: ["vencido", "leche", "recibo", "cambiar", "ayer"],
    user_audio: "mp3 file",
    created_at: "2025-08-07T13:15:00Z"
  },
  {
    id: "f8a9b0c1-d2e3-4567-bcde-8901234567fa",
    session_id: "sess_2025_018",
    user_id: "user_123",
    title: "Package missing",
    role_scenario: "email amazon because tracking says delivered but you didn't get package",
    feedback: "- **Tracking says delivered** → *el seguimiento dice entregado*\n- **I didn’t receive it** → *no lo recibí*\n- **Can you check?** → *¿Puede revisar?*\n- You wrote *no lo tengo*; more formal *no lo recibí*",
    target_vocabulary: ["paquete", "seguimiento", "entregado", "recibir", "revisar"],
    user_audio: "mp3 file",
    created_at: "2025-08-07T13:30:00Z"
  },
  {
    id: "a9b0c1d2-e3f4-5678-cdef-9012345678ab",
    session_id: "sess_2025_019",
    user_id: "user_123",
    title: "Haircut too short",
    role_scenario: "tell barber he cut your hair shorter than you asked show photo what you wanted",
    feedback: "- **Shorter than I wanted** → *más corto de lo que quería*\n- **This is the style** → *este es el estilo*\n- **Can you fix it?** → *¿Puede arreglarlo?*\n- You said *muy corto*; add comparison *de lo que*",
    target_vocabulary: ["más corto", "estilo", "arreglar", "foto", "barbero"],
    user_audio: "mp3 file",
    created_at: "2025-08-07T13:45:00Z"
  },
  {
    id: "b0c1d2e3-f4a5-6789-defa-0123456789bc",
    session_id: "sess_2025_020",
    user_id: "user_123",
    title: "Propose toast",
    role_scenario: "at wedding you are best man need to give short toast in spanish to couple",
    feedback: "- **Dear friends** → *queridos amigos*\n- **To the couple** → *por la pareja*\n- **Wish you happiness** → *les deseo felicidad*\n- You said *para la pareja*; *por* is for toasts",
    target_vocabulary: ["brindis", "pareja", "felicidad", "queridos", "esposos"],
    user_audio: "mp3 file",
    created_at: "2025-08-07T14:00:00Z"
  },
  {
    id: "c1d2e3f4-a5b6-7890-abcd-1234567890cd",
    session_id: "sess_2025_021",
    user_id: "user_123",
    title: "Report dog poop",
    role_scenario: "call city hall to report neighbor never cleans up dog poop in front of your door",
    feedback: "- **Never cleans up** → *nunca recoge*\n- **In front of my door** → *frente a mi puerta*\n- **Dog poop** → *excrementos de perro*\n- You said *caca de perro*; more formal *excrementos*",
    target_vocabulary: ["excrementos", "recoger", "vecino", "frente", "queja"],
    user_audio: "mp3 file",
    created_at: "2025-08-07T14:15:00Z"
  },
  {
    id: "d2e3f4a5-b6c7-8901-bcde-2345678901de",
    session_id: "sess_2025_022",
    user_id: "user_123",
    title: "Late rent",
    role_scenario: "text landlord rent will be 5 days late because your salary got delayed",
    feedback: "- **Will be late** → *llegará tarde*\n- **Salary delayed** → *mi salario se retrasó*\n- **Five days** → *cinco días*\n- You said *mi pago es tarde*; verb *llegará*",
    target_vocabulary: ["alquiler", "retrasado", "salario", "cinco días", "disculpa"],
    user_audio: "mp3 file",
    created_at: "2025-08-07T14:30:00Z"
  },
  {
    id: "e3f4a5b6-c7d8-9012-cdef-3456789012ef",
    session_id: "sess_2025_023",
    user_id: "user_123",
    title: "Meeting reschedule",
    role_scenario: "email client to move tuesday 3pm meeting to friday same time because of doctor appointment",
    feedback: "- **Move the meeting** → *reprogramar la reunión*\n- **Tuesday to Friday** → *del martes al viernes*\n- **Same time** → *a la misma hora*\n- You forgot to mention reason",
    target_vocabulary: ["reprogramar", "reunión", "martes", "viernes", "cita médica"],
    user_audio: "mp3 file",
    created_at: "2025-08-07T14:45:00Z"
  },
  {
    id: "f4a5b6c7-d8e9-0123-defa-4567890123fa",
    session_id: "sess_2025_024",
    user_id: "user_123",
    title: "No hot water",
    role_scenario: "call building maintenance because no hot water in your apartment since morning",
    feedback: "- **No hot water** → *no hay agua caliente*\n- **Since morning** → *desde esta mañana*\n- **Can you check?** → *¿Puede revisar?*\n- You said *agua caliente no funciona*; better *no hay*",
    target_vocabulary: ["agua caliente", "mañana", "revisar", "mantenimiento"],
    user_audio: "mp3 file",
    created_at: "2025-08-07T15:00:00Z"
  },
  {
    id: "a5b6c7d8-e9f0-1234-efab-5678901234ab",
    session_id: "sess_2025_025",
    user_id: "user_123",
    title: "Group project",
    role_scenario: "ask classmate to send you the presentation slides because your laptop crashed",
    feedback: "- **Send me slides** → *envíame las diapositivas*\n- **Laptop crashed** → *mi computadora se estropeó*\n- **Group project** → *trabajo en grupo*\n- You said *mandar*; *enviar* is neutral",
    target_vocabulary: ["diapositivas", "enviar", "computadora", "estropearse", "trabajo"],
    user_audio: "mp3 file",
    created_at: "2025-08-07T15:15:00Z"
  },
    {
    id: "b6c7d8e9-f0a1-2345-fabc-6789012345bc",
    session_id: "sess_2025_026",
    user_id: "user_123",
    title: "Mom's birthday gift",
    role_scenario: "ask your siblings in group chat what to get mom for her 60th birthday next month",
    feedback: "- **Next month** → *el mes que viene*\n- **Turns 60** → *cumple 60 años*\n- **What should we get** → *¿qué le regalamos?*\n- You wrote *60 cumpleaños*; add *años*",
    target_vocabulary: ["regalo", "cumpleaños", "hermanos", "mes que viene", "madre"],
    user_audio: "mp3 file",
    created_at: "2025-08-07T15:30:00Z"
  },
  {
    id: "c7d8e9f0-a1b2-3456-abcd-7890123456cd",
    session_id: "sess_2025_027",
    user_id: "user_123",
    title: "Refund request",
    role_scenario: "message online shop the shoes arrived damaged and you want full refund not exchange",
    feedback: "- **Arrived damaged** → *llegaron dañados*\n- **Full refund** → *reembolso completo*\n- **Not exchange** → *no un cambio*\n- You wrote *dañado*; plural *dañados* matches shoes",
    target_vocabulary: ["dañado", "reembolso", "completo", "zapatos", "devolución"],
    user_audio: "mp3 file",
    created_at: "2025-08-07T15:45:00Z"
  },
  {
    id: "d8e9f0a1-b2c3-4567-bcde-8901234567de",
    session_id: "sess_2025_028",
    user_id: "user_123",
    title: "Pick up kids",
    role_scenario: "text your mom to pick up kids from school today because you're stuck in traffic",
    feedback: "- **Pick up** → *recoger* not *recojer*\n- **Stuck in traffic** → *atascado en el tráfico*\n- **Today** → *hoy*\n- You wrote *recojer*; spelling *recoger*",
    target_vocabulary: ["recoger", "niños", "atascado", "tráfico", "hoy"],
    user_audio: "mp3 file",
    created_at: "2025-08-07T16:00:00Z"
  },
  {
    id: "e9f0a1b2-c3d4-5678-cdef-9012345678ef",
    session_id: "sess_2025_029",
    user_id: "user_123",
    title: "Room too noisy",
    role_scenario: "tell hotel reception your room faces street and is too loud to sleep ask for room change",
    feedback: "- **Faces the street** → *da a la calle*\n- **Too loud** → *demasiado ruidoso*\n- **Can I change rooms?** → *¿Puedo cambiar de habitación?*\n- You said *room is noisy*; add *demasiado*",
    target_vocabulary: ["ruidoso", "calle", "cambiar", "habitación", "dormir"],
    user_audio: "mp3 file",
    created_at: "2025-08-07T16:15:00Z"
  },
  {
    id: "f0a1b2c3-d4e5-6789-defa-0123456789fa",
    session_id: "sess_2025_030",
    user_id: "user_123",
    title: "Loan repayment",
    role_scenario: "ask friend when he can pay back the 200 euros you lent him last month",
    feedback: "- **Pay back** → *devolver* not *pagar atrás*\n- **Lent last month** → *te presté el mes pasado*\n- **200 euros** → *doscientos euros*\n- You asked *cuándo pagas*; add *devolver*",
    target_vocabulary: ["devolver", "prestar", "doscientos", "mes pasado", "dinero"],
    user_audio: "mp3 file",
    created_at: "2025-08-07T16:30:00Z"
  },
  {
    id: "a1b2c3d4-e5f6-7890-abcd-1234567890ab",
    session_id: "sess_2025_031",
    user_id: "user_123",
    title: "Dry cleaning lost",
    role_scenario: "call dry cleaner they lost your white shirt you dropped last week need it for wedding",
    feedback: "- **Lost my shirt** → *perdieron mi camisa*\n- **Dropped last week** → *la dejé la semana pasada*\n- **Need for wedding** → *la necesito para una boda*\n- You said *camisa perdido*; verb *perdieron*",
    target_vocabulary: ["camisa", "perdido", "lavandería", "boda", "semana pasada"],
    user_audio: "mp3 file",
    created_at: "2025-08-07T16:45:00Z"
  },
  {
    id: "b2c3d4e5-f6a7-8901-bcde-2345678901bc",
    session_id: "sess_2025_032",
    user_id: "user_123",
    title: "Quit tutoring job",
    role_scenario: "tell your private english student you can't continue lessons because new full time job",
    feedback: "- **I have to stop** → *tengo que dejar las clases*\n- **New full-time job** → *nuevo trabajo a tiempo completo*\n- **Thanks for understanding** → *gracias por entender*\n- You said *no puedo más*; better explain reason",
    target_vocabulary: ["dejar", "clases", "trabajo completo", "entender", "gracias"],
    user_audio: "mp3 file",
    created_at: "2025-08-07T17:00:00Z"
  },
  {
    id: "c3d4e5f6-a7b8-9012-cdef-3456789012cd",
    session_id: "sess_2025_033",
    user_id: "user_123",
    title: "Lost passport",
    role_scenario: "call embassy to report you lost your passport at metro station this morning",
    feedback: "- **Lost passport** → *perdí el pasaporte*\n- **At metro station** → *en la estación de metro*\n- **This morning** → *esta mañana*\n- You said *pasaporte perdido*; use verb *perdí*",
    target_vocabulary: ["pasaporte", "perder", "embajada", "metro", "mañana"],
    user_audio: "mp3 file",
    created_at: "2025-08-07T17:15:00Z"
  },
  {
    id: "d4e5f6a7-b8c9-0123-defa-4567890123de",
    session_id: "sess_2025_034",
    user_id: "user_123",
    title: "Surprise proposal",
    role_scenario: "ask girlfriend's best friend to help you plan surprise proposal at restaurant next friday",
    feedback: "- **Help me plan** → *ayúdame a planear*\n- **Surprise proposal** → *propuesta sorpresa*\n- **Next Friday** → *el próximo viernes*\n- You said *pedir matrimonio*; *propuesta* is common",
    target_vocabulary: ["propuesta", "sorpresa", "restaurante", "viernes", "ayudar"],
    user_audio: "mp3 file",
    created_at: "2025-08-07T17:30:00Z"
  },
  {
    id: "e5f6a7b8-c9d0-1234-efab-5678901234ef",
    session_id: "sess_2025_035",
    user_id: "user_123",
    title: "Movie spoilers",
    role_scenario: "tell coworker not to spoil new movie you haven't watched yet",
    feedback: "- **Don’t spoil it** → *no me lo arruines*\n- **Haven’t watched yet** → *aún no la he visto*\n- **New movie** → *la nueva película*\n- You said *no spoilers*; *arruinar* is natural",
    target_vocabulary: ["arruinar", "película", "aún no", "espoiler"],
    user_audio: "mp3 file",
    created_at: "2025-08-07T17:45:00Z"
  },
  {
    id: "f6a7b8c9-d0e1-2345-fabc-6789012345fa",
    session_id: "sess_2025_036",
    user_id: "user_123",
    title: "Refund bus ticket",
    role_scenario: "call bus company to refund ticket because you tested positive for covid and can't travel",
    feedback: "- **Tested positive** → *di positivo*\n- **Can't travel** → *no puedo viajar*\n- **Request refund** → *solicitar reembolso*\n- You said *tengo covid*; add *di positivo* for clarity",
    target_vocabulary: ["covid", "positivo", "reembolso", "viaje", "autobús"],
    user_audio: "mp3 file",
    created_at: "2025-08-07T18:00:00Z"
  },
  {
    id: "a7b8c9d0-e1f2-3456-abcd-7890123456ab",
    session_id: "sess_2025_037",
    user_id: "user_123",
    title: "Wrong pizza",
    role_scenario: "call pizzeria they delivered pepperoni but you ordered vegetarian and want replacement",
    feedback: "- **Wrong pizza** → *pizza equivocada*\n- **I ordered vegetarian** → *pedí vegetariana*\n- **Want replacement** → *quiero que la cambien*\n- You said *pizza incorrecta*; *equivocada* is common",
    target_vocabulary: ["equivocada", "vegetariana", "cambiar", "pizzería"],
    user_audio: "mp3 file",
    created_at: "2025-08-07T18:15:00Z"
  },
  {
    id: "b8c9d0e1-f2a3-4567-bcde-8901234567bc",
    session_id: "sess_2025_038",
    user_id: "user_123",
    title: "Doctor reschedule",
    role_scenario: "call dentist to move tomorrow appointment to next week due to work trip",
    feedback: "- **Need to reschedule** → *necesito cambiar la cita*\n- **Work trip** → *viaje de trabajo*\n- **Next week** → *la semana que viene*\n- You said *mover*; *cambiar* is standard",
    target_vocabulary: ["cambiar", "cita", "viaje", "trabajo", "semana"],
    user_audio: "mp3 file",
    created_at: "2025-08-07T18:30:00Z"
  },
  {
    id: "c9d0e1f2-a3b4-5678-cdef-9012345678cd",
    session_id: "sess_2025_039",
    user_id: "user_123",
    title: "Invite neighbors",
    role_scenario: "knock on neighbor's door to invite them to housewarming party this saturday at 7pm",
    feedback: "- **Housewarming party** → *fiesta de inauguración*\n- **This Saturday at 7** → *este sábado a las siete*\n- **Hope you can come** → *espero que puedan venir*\n- You said *party en mi casa*; *fiesta de inauguración* is clearer",
    target_vocabulary: ["inauguración", "sábado", "invitar", "vecinos", "esperar"],
    user_audio: "mp3 file",
    created_at: "2025-08-07T18:45:00Z"
  },
  {
    id: "d0e1f2a3-b4c5-6789-defa-0123456789de",
    session_id: "sess_2025_040",
    user_id: "user_123",
    title: "Ask for raise",
    role_scenario: "schedule meeting with boss to ask for salary increase after 18 months at company",
    feedback: "- **Schedule meeting** → *agendar una reunión*\n- **Salary increase** → *aumento salarial*\n- **18 months** → *dieciocho meses*\n- You said *subir salario*; *aumento* is formal",
    target_vocabulary: ["aumento", "reunión", "salario", "meses", "empresa"],
    user_audio: "mp3 file",
    created_at: "2025-08-07T19:00:00Z"
  },
  {
    id: "e1f2a3b4-c5d6-7890-abcd-1234567890ef",
    session_id: "sess_2025_041",
    user_id: "user_123",
    title: "Flight delay",
    role_scenario: "announcement says flight delayed 3 hours ask gate agent if hotel provided",
    feedback: "- **Delayed 3 hours** → *retrasado tres horas*\n- **Hotel provided** → *proporcionan hotel*\n- **Ask gate agent** → *preguntar al agente*\n- You said *hotel gratis*; *proporcionan* is formal",
    target_vocabulary: ["retrasado", "hotel", "proporcionar", "agente", "horas"],
    user_audio: "mp3 file",
    created_at: "2025-08-07T19:15:00Z"
  },
  {
    id: "f2a3b4c5-d6e7-8901-bcde-2345678901fa",
    session_id: "sess_2025_042",
    user_id: "user_123",
    title: "Bank loan",
    role_scenario: "ask bank for small loan to buy used car explain you have stable job",
    feedback: "- **Small loan** → *préstamo pequeño*\n- **Used car** → *coche de segunda mano*\n- **Stable job** → *trabajo estable*\n- You said *dinero para coche*; specify *préstamo*",
    target_vocabulary: ["préstamo", "coche", "segunda mano", "trabajo", "estable"],
    user_audio: "mp3 file",
    created_at: "2025-08-07T19:30:00Z"
  },
  {
    id: "a3b4c5d6-e7f8-9012-cdef-3456789012ab",
    session_id: "sess_2025_043",
    user_id: "user_123",
    title: "Cancel gym",
    role_scenario: "call gym to cancel membership because you moved to another city",
    feedback: "- **Cancel membership** → *cancelar la membresía*\n- **Moved to another city** → *me mudé a otra ciudad*\n- **Effective immediately** → *con efecto inmediato*\n- You said *stop gym*; use *cancelar*",
    target_vocabulary: ["cancelar", "membresía", "mudarse", "ciudad", "inmediato"],
    user_audio: "mp3 file",
    created_at: "2025-08-07T19:45:00Z"
  },
  {
    id: "b4c5d6e7-f8a9-0123-defa-4567890123bc",
    session_id: "sess_2025_044",
    user_id: "user_123",
    title: "Surprise wife",
    role_scenario: "ask wife's best friend to help plan surprise weekend getaway for anniversary",
    feedback: "- **Weekend getaway** → *escapada de fin de semana*\n- **Anniversary** → *aniversario*\n- **Help me plan** → *ayúdame a planear*\n- You said *sorpresa viaje*; *escapada* is common",
    target_vocabulary: ["escapada", "aniversario", "sorpresa", "planear", "amiga"],
    user_audio: "mp3 file",
    created_at: "2025-08-07T20:00:00Z"
  },
  {
    id: "c5d6e7f8-a9b0-1234-efab-5678901234cd",
    session_id: "sess_2025_045",
    user_id: "user_123",
    title: "Report harassment",
    role_scenario: "call hr to report coworker keeps making inappropriate comments to you",
    feedback: "- **Inappropriate comments** → *comentarios inapropiados*\n- **Keeps making** → *sigue haciendo*\n- **Report to HR** → *reportar a recursos humanos*\n- You said *bad words*; *inapropiados* is clearer",
    target_vocabulary: ["acoso", "inapropiado", "comentarios", "recursos humanos", "reportar"],
    user_audio: "mp3 file",
    created_at: "2025-08-07T20:15:00Z"
  },
  {
    id: "d6e7f8a9-b0c1-2345-fabc-6789012345de",
    session_id: "sess_2025_046",
    user_id: "user_123",
    title: "Dentist reminder",
    role_scenario: "call mom to remind her about dentist appointment tomorrow at 10am",
    feedback: "- **Reminder** → *recordatorio*\n- **Tomorrow at 10** → *mañana a las diez*\n- **Don’t forget** → *no olvides*\n- You said *mañana 10*; add *a las*",
    target_vocabulary: ["recordatorio", "dentista", "mañana", "diez", "no olvidar"],
    user_audio: "mp3 file",
    created_at: "2025-08-07T20:30:00Z"
  },
  {
    id: "e7f8a9b0-c1d2-3456-abcd-7890123456ef",
    session_id: "sess_2025_047",
    user_id: "user_123",
    title: "Wrong order",
    role_scenario: "tell delivery driver this isn't your food you ordered sushi they brought pizza",
    feedback: "- **Wrong order** → *pedido equivocado*\n- **I ordered sushi** → *pedí sushi*\n- **You brought pizza** → *trajeron pizza*\n- You said *no es mi comida*; specify order",
    target_vocabulary: ["pedido", "equivocado", "sushi", "pizza", "entrega"],
    user_audio: "mp3 file",
    created_at: "2025-08-07T20:45:00Z"
  },
  {
    id: "f8a9b0c1-d2e3-4567-bcde-8901234567fa",
    session_id: "sess_2025_048",
    user_id: "user_123",
    title: "Birthday party",
    role_scenario: "ask venue if they have availability for 30th birthday party next saturday 7pm-12am",
    feedback: "- **Availability** → *disponibilidad*\n- **30th birthday** → *cumpleaños 30*\n- **7pm to 12am** → *de 7 a 12*\n- You said *saturday night*; specify times",
    target_vocabulary: ["disponibilidad", "cumpleaños", "sábado", "salón", "hora"],
    user_audio: "mp3 file",
    created_at: "2025-08-07T21:00:00Z"
  },
  {
    id: "a9b0c1d2-e3f4-5678-cdef-9012345678ab",
    session_id: "sess_2025_049",
    user_id: "user_123",
    title: "Interview prep",
    role_scenario: "ask friend to do mock interview with you for sales manager position tomorrow",
    feedback: "- **Mock interview** → *entrevista simulada*\n- **Sales manager** → *gerente de ventas*\n- **Tomorrow** → *mañana*\n- You said *práctica entrevista*; *simulada* is clearer",
    target_vocabulary: ["entrevista", "simulada", "gerente", "ventas", "práctica"],
    user_audio: "mp3 file",
    created_at: "2025-08-07T21:15:00Z"
  },
  {
    id: "b0c1d2e3-f4a5-6789-defa-0123456789bc",
    session_id: "sess_2025_050",
    user_id: "user_123",
    title: "Apologize late",
    role_scenario: "text date you're running 20 minutes late because traffic is bad",
    feedback: "- **Running late** → *llegaré tarde*\n- **20 minutes** → *veinte minutos*\n- **Traffic is bad** → *el tráfico está pesado*\n- You said *soy tarde*; *llegaré tarde*",
    target_vocabulary: ["llegar tarde", "veinte", "tráfico", "pesado", "disculpa"],
    user_audio: "mp3 file",
    created_at: "2025-08-07T21:30:00Z"
  }
]